### ISSUE TITLE
NEXUS file is incomplete when downloaded

### ISSUE THREAD

**Issue by Ewout1988** [rega-cev/phylogeotool#30]
Fix the problem that the downloaded NEXUS file is incomplete.
This is most likely due to using an older JEBL library. Updating the library should fix the issue

**Comment by Ewout1988** [comment]
This bug should be fixed. Wait with closing the issue until it has been deployed and tested online

**Comment by GuyBaele** [comment]
File is still incomplete for dengue instance (and NEXUS opens in a new tab rather than presenting a downloadable file).

**Comment by GuyBaele** [comment]
Seems to work on euresist example.

**Comment by Ewout1988** [comment]
It should now work for Dengue as well (Dengue wasn't redeployed)

**Comment by GuyBaele** [comment]
Works on my Mac.
