### ISSUE TITLE
Provide tree downloads as files, not written text

### ISSUE THREAD

**Issue by Ewout1988** [rega-cev/phylogeotool#31]
Currently the exported trees are sometimes displayed as written text (e.g. download as NEXUS file) instead of a file that downloads to the user's computer.

**Comment by Ewout1988** [comment]
I've changed the MIME-type of the NEXUS file from "text/plain" to "application/nexus" such that the content will be offered as a file instead of displayed in the browser.
Wait with closing until this has been tested

**Comment by GuyBaele** [comment]
I'm testing this, but no file is being downloaded (NEXUS format); a new tab is opened in my browser instead. Also, when I download this text and plot it in FigTree, it only contains a few sequences. Tested on the dengue example.

**Comment by GuyBaele** [comment]
This does work for the euresist example, so perhaps the dengue wasn't deployed anew.

**Comment by Ewout1988** [comment]
This should now be working for the Dengue example as well (only EUResist was indeed redeployed)

**Comment by GuyBaele** [comment]
Working fine on my Mac.
